/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.3.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Monday, August 5, 2019
 ***********************************************************************************************/

#ifndef LEDS_INTERFACE_H
#define LEDS_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../mxchip_iot_devkit_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

// DigitalTwin interface name from service perspective.
static const char LedsInterfaceId[] = "urn:mxchip:built_in_leds:1";
static const char LedsComponentName[] = "leds";

// Telemetry names for this interface.

// Property names for this interface.

// Command names for this interface

#define LedsInterface_BlinkCommand "blink"

#define LedsInterface_TurnOnLedCommand "turnOnLed"

#define LedsInterface_TurnOffLedCommand "turnOffLed"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE LedsInterface_Create();

void LedsInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

#ifdef __cplusplus
}
#endif

#endif  // LEDS_INTERFACE_H
