/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.3.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Monday, August 5, 2019
 ***********************************************************************************************/

#ifndef MODELDEFINITION_INTERFACE_H
#define MODELDEFINITION_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../mxchip_iot_devkit_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

// DigitalTwin interface name from service perspective.
static const char ModelDefinitionInterfaceId[] = "urn:azureiot:ModelDiscovery:ModelDefinition:1";
static const char ModelDefinitionComponentName[] = "modelDefinition";

// Telemetry names for this interface.

// Property names for this interface.

// Command names for this interface

#define ModelDefinitionInterface_GetModelDefinitionCommand "getModelDefinition"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE ModelDefinitionInterface_Create();

void ModelDefinitionInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

#ifdef __cplusplus
}
#endif

#endif  // MODELDEFINITION_INTERFACE_H
