/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.3.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Monday, August 5, 2019
 ***********************************************************************************************/

#ifndef SYSTEM_INTERFACE_H
#define SYSTEM_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/uuid.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../mxchip_iot_devkit_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum SYSTEM_REBOOT_STATUS_TAG
{
    SYSTEM_REBOOT_INACTIVE,
    SYSTEM_REBOOT_RUNNING,
    SYSTEM_REBOOT_COMPLETED,
    SYSTEM_REBOOT_ERROR
} SYSTEM_REBOOT_STATUS;

// DigitalTwin interface name from service perspective.
static const char SystemInterfaceId[] = "urn:mxchip:system:1";
static const char SystemComponentName[] = "system";

// Telemetry names for this interface.

// Property names for this interface.

// Command names for this interface

#define SystemInterface_RebootCommand "reboot"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE SystemInterface_Create();

void SystemInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT SystemInterface_Reboot_UpdateStatus(SYSTEM_REBOOT_STATUS commandStatus, int statusCode);

#ifdef __cplusplus
}
#endif

#endif  // SYSTEM_INTERFACE_H
